name: Deploy Next.js app to server

on:
  push:
    branches:
      - master  # Пуш в основную ветку (или любую другую ветку, которую вы хотите использовать для деплоя)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Убедитесь, что версия Node.js соответствует вашей

      - name: Install dependencies
        run: |
          npm install --production

      - name: Build the app
        run: |
          npm run build

      - name: Upload packages to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -p 22220 -o StrictHostKeyChecking=no -i private_key.pem $USER@$SERVER_IP << 'EOF'
            cd /var/react-table
          
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsaserv
          
            # Выполнение git pull с проверкой на ошибку
            git pull origin master || { echo 'Git pull failed: Permission denied (publickey)'; exit 1; }
          
            npm install --production
            rm -rf .next  
          EOF

      - name: Copy build artifacts to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.USER }}
        run: |
          # Копирование артефактов билда на сервер
          scp -i private_key.pem -P 22220 -r .next $USER@$SERVER_IP:/var/react-table

      - name: Restart pm2 process
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.USER }}
        run: |
          # Подготовка SSH ключа
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -p 22220 -o StrictHostKeyChecking=no -i private_key.pem $USER@$SERVER_IP << 'EOF'
            pm2 restart react-table  # Перезапуск приложения
          EOF